### ISSUE TITLE
Feature request: Add possibility to configure name for TOTP

### ISSUE THREAD

**Issue by ziggekatten** [k1nky/netbox-otp-plugin#1]
The plugin works like it should. However, adding the QR-code to Google Authenticator, it's added with the username as description. It would be great to configure this, since in my case I have the same username in three different environments, dev, test and prod, and would like to be able to name them differently automatically (for example: Netbox DEV)

**Comment by k1nky** [comment]
Thank you for the request.

There are two ways to do it now. You can use the plugin option `issuer` (see more in [README)](https://github.com/k1nky/netbox-otp-plugin#configuration) or set `OTP_TOTP_ISSUER` options in settings.py (djano-otp has already supported to customize OTP label). The first way is more preferred because it allows to avoid making any changes in the original settings.py.
