### ISSUE TITLE
Django admin UI removed in later Netbox v4 versions

### ISSUE THREAD

**Issue by Creepios** [k1nky/netbox-otp-plugin#10]
Hello,
please add an option to add otp tokens over the normal UI. As stated in the netbox issue #16136, the Django admin ui will be removed. https://github.com/netbox-community/netbox/issues/16136

@marco012024 Could you implement this in your fork? This would be wonderful.

**Comment by k1nky** [comment]
Hello, thank you for your issue.

I've been working about it.
The plugin is based on the django-otp project. That project provides device management in the admin section. It is not so easy to use models from django-otp in the new interface due to the management of restrictions in NetBox. Anyway it would be better to decouple from django-otp and transfer the main functionality to the plugin.

I have tried it and it's possible. As result I see that the device management in the new UI should work.

**Comment by k1nky** [comment]
Release [v1.2.0](https://github.com/k1nky/netbox-otp-plugin/releases/tag/v1.2.0) adds OTP device management in the NetBox interface.
